### PR TITLE
Update 1_access_violation.asm

### PR DESCRIPTION
**Pull request by arman-k**
Fix minor error in comment.

### CODE REVIEW

**Comment by xorpd** [comment]
You are sharp :)

**Comment by arman-k** [comment]
Thanks for producing these wonderful exercises! They immensely helped me solidify my noob understanding of x86 asm, and I must admit that they contributed to my newfound love for assembly. Now that I am done with all the exercises, could you suggest me a few interesting project ideas? You could perhaps consider adding it to your repository as well, something that beginners can try out after completing all the exercises. I believe some additional pointers on how to take it on from there would be really helpful too! 

Thanks again, xorpd! :)

**Comment by xorpd** [comment]
Hi arman-k, my pleasure.
Some things you can check now:
- You can learn about some GUI programming for windows from IcZelion's tutorials: http://win32assembly.programminghorizon.com/ . They are a bit dated and written in masm32, but all x86 assemblers are pretty similar and you can probably find your way through it.
- Look at the fasm examples: http://flatassembler.net/examples.php as inspiration for interesting things that you can do.
- "xchg rax,rax", at http://xchg.xorpd.net can teach you about tricks in x64 assembly. It is a list of very short assembly riddles about x64.

**Comment by arman-k** [comment]
Thanks xorpd! I will check them out for sure.

**Pull request merged**
